using Microsoft.Extensions.Caching.Distributed;

namespace ScoramAPI.Services
{
    public interface ICaptchaService
    {
        /// <summary>Generates a new challenge and stashes its answer server-side, keyed by the
        /// returned CaptchaId. Nothing about the answer is ever sent to the client -- see
        /// Verify's own comment on why that matters.</summary>
        (string CaptchaId, string Question) Generate();

        /// <summary>One-time check: correct-or-not, the challenge is consumed either way (removed
        /// from cache) so the same CaptchaId can never be replayed, whether the first attempt was
        /// right or wrong. Callers that want another try need to call Generate() again for a fresh
        /// CaptchaId -- exactly how a real captcha image would work too.</summary>
        bool Verify(string captchaId, int answer);
    }

    // A DELIBERATELY LOW-TECH CAPTCHA -- a simple arithmetic question ("7 + 4 = ?"), not Google
    // reCAPTCHA/hCaptcha/an image with distorted text. This stops the overwhelming majority of
    // real-world abuse (scripted mass account creation, credential-stuffing scripts hammering
    // Login) without needing a third-party account, a site key, or a Play Services/App Store
    // review dependency for something a Flutter app would otherwise need a WebView or a paid
    // Enterprise SDK to embed. It will NOT stop a targeted human attacker or an attacker willing to
    // wire up an LLM to read the question -- if that threat model ever becomes real for Scoram
    // (e.g. this stops being enough), swap this service's Generate/Verify for a real reCAPTCHA/
    // hCaptcha server-side verify call; nothing else (AuthController's two call sites, or the
    // mobile widget) needs to change shape to support that later.
    //
    // STATE LIVES IN IDistributedCache -- Redis-backed when ConnectionStrings:Redis is configured,
    // an in-memory fallback otherwise (see Program.cs). Kept fully synchronous here (IDistributedCache
    // has sync Get/Set/Remove alongside the async versions) so this service's public API, and both
    // AuthController call sites, don't need to become async just for this -- a captcha check is a
    // fast, incidental part of a bigger request, not something worth threading Task through for.
    // Before this moved off IMemoryCache, a captcha generated by one instance couldn't be verified by
    // a different one behind a load balancer without sticky sessions; now that's only still true if
    // Redis isn't configured, same as everything else in this codebase that uses this cache.
    public class CaptchaService : ICaptchaService
    {
        private const string CachePrefix = "captcha:";
        private static readonly DistributedCacheEntryOptions CacheOptions =
            new() { AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(5) };
        private static readonly char[] Operators = { '+', '-', '×' };

        private readonly IDistributedCache _cache;
        private readonly Random _random = new();

        public CaptchaService(IDistributedCache cache)
        {
            _cache = cache;
        }

        public (string CaptchaId, string Question) Generate()
        {
            var a = _random.Next(1, 10);
            var b = _random.Next(1, 10);
            var op = Operators[_random.Next(Operators.Length)];

            // Keep subtraction non-negative -- "3 - 7 = ?" is needlessly confusing for what's meant
            // to be a two-second speed bump, not a math test.
            if (op == '-' && b > a) (a, b) = (b, a);

            var answer = op switch
            {
                '+' => a + b,
                '-' => a - b,
                '×' => a * b,
                _ => a + b
            };

            var captchaId = Guid.NewGuid().ToString("N");
            _cache.SetString(CachePrefix + captchaId, answer.ToString(), CacheOptions);

            return (captchaId, $"{a} {op} {b} = ?");
        }

        public bool Verify(string captchaId, int answer)
        {
            var key = CachePrefix + captchaId;
            var stored = _cache.GetString(key);
            if (stored == null || !int.TryParse(stored, out var correctAnswer)) return false;

            // Consumed on first use regardless of outcome -- see the interface method's own comment.
            _cache.Remove(key);

            return correctAnswer == answer;
        }
    }
}
