using Microsoft.Extensions.Caching.Memory;

namespace ScoramAPI.Services
{
    public interface ICaptchaService
    {
        /// <summary>Generates a new challenge and stashes its answer server-side, keyed by the
        /// returned CaptchaId. Nothing about the answer is ever sent to the client -- see
        /// Verify's own comment on why that matters.</summary>
        (string CaptchaId, string Question) Generate();

        /// <summary>One-time check: correct-or-not, the challenge is consumed either way (removed
        /// from cache) so the same CaptchaId can never be replayed, whether the first attempt was
        /// right or wrong. Callers that want another try need to call Generate() again for a fresh
        /// CaptchaId -- exactly how a real captcha image would work too.</summary>
        bool Verify(string captchaId, int answer);
    }

    // A DELIBERATELY LOW-TECH CAPTCHA -- a simple arithmetic question ("7 + 4 = ?"), not Google
    // reCAPTCHA/hCaptcha/an image with distorted text. This stops the overwhelming majority of
    // real-world abuse (scripted mass account creation, credential-stuffing scripts hammering
    // Login) without needing a third-party account, a site key, or a Play Services/App Store
    // review dependency for something a Flutter app would otherwise need a WebView or a paid
    // Enterprise SDK to embed. It will NOT stop a targeted human attacker or an attacker willing to
    // wire up an LLM to read the question -- if that threat model ever becomes real for Scoram
    // (e.g. this stops being enough), swap this service's Generate/Verify for a real reCAPTCHA/
    // hCaptcha server-side verify call; nothing else (AuthController's two call sites, or the
    // mobile widget) needs to change shape to support that later.
    //
    // STATE LIVES IN IMemoryCache -- same "short-lived server-side staging, not a DB table" pattern
    // BulkImportController/QuestionBankAdminController already use for import previews (see
    // BulkImportStagingCleanupService's own comment on that pattern). The one thing worth knowing:
    // this is per-process. If ScoramAPI is ever deployed as more than one instance behind a load
    // balancer without sticky sessions, a captcha generated by instance A won't be found by
    // instance B -- Verify would then always return false for a fraction of requests, not because
    // the answer was wrong but because the load balancer picked a different instance in between.
    // Fine for a single-instance deployment (which is what everything else using IMemoryCache in
    // this codebase already assumes); revisit with a distributed cache (Redis, or a DB row) before
    // scaling ScoramAPI horizontally.
    public class CaptchaService : ICaptchaService
    {
        private const string CachePrefix = "captcha:";
        private static readonly TimeSpan Ttl = TimeSpan.FromMinutes(5);
        private static readonly char[] Operators = { '+', '-', '×' };

        private readonly IMemoryCache _cache;
        private readonly Random _random = new();

        public CaptchaService(IMemoryCache cache)
        {
            _cache = cache;
        }

        public (string CaptchaId, string Question) Generate()
        {
            var a = _random.Next(1, 10);
            var b = _random.Next(1, 10);
            var op = Operators[_random.Next(Operators.Length)];

            // Keep subtraction non-negative -- "3 - 7 = ?" is needlessly confusing for what's meant
            // to be a two-second speed bump, not a math test.
            if (op == '-' && b > a) (a, b) = (b, a);

            var answer = op switch
            {
                '+' => a + b,
                '-' => a - b,
                '×' => a * b,
                _ => a + b
            };

            var captchaId = Guid.NewGuid().ToString("N");
            _cache.Set(CachePrefix + captchaId, answer, Ttl);

            return (captchaId, $"{a} {op} {b} = ?");
        }

        public bool Verify(string captchaId, int answer)
        {
            var key = CachePrefix + captchaId;
            if (!_cache.TryGetValue(key, out int correctAnswer)) return false;

            // Consumed on first use regardless of outcome -- see the interface method's own comment.
            _cache.Remove(key);

            return correctAnswer == answer;
        }
    }
}
